# Generated by Django 5.2.5 on 2025-10-10 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_onetimecode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='onetimecode',
            options={'verbose_name': 'Одноразовый код', 'verbose_name_plural': 'Одноразовые коды'},
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='action',
            field=models.CharField(choices=[('change_email', 'Смена почты'), ('delete_account', 'Удаление аккаунта')], db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='code',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_time_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='onetimecode',
            name='value',
            field=models.CharField(help_text='Целевое значение (новая почта или текущая почта)', max_length=255),
        ),
        migrations.AddIndex(
            model_name='onetimecode',
            index=models.Index(fields=['user', 'action', 'created_at'], name='users_oneti_user_id_ddac9f_idx'),
        ),
    ]
