# Generated by Django 5.2.5 on 2025-10-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_onetimecode_options_alter_onetimecode_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='code',
            field=models.CharField(db_index=True, max_length=6, unique=True),
        ),
    ]
