# Generated by Django 5.2.5 on 2025-10-10 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_emailverification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='onetimecode',
            unique_together={('user', 'action', 'code')},
        ),
        migrations.AddIndex(
            model_name='emailverification',
            index=models.Index(fields=['user', 'created_at'], name='users_email_user_id_61fb2b_idx'),
        ),
    ]
