# Generated by Django 5.2.5 on 2025-08-28 18:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='TranslatorPublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('manga_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title_ru', models.CharField(db_index=True, max_length=255)),
                ('title_en', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('alt_titles', models.JSONField(blank=True, default=list)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('type', models.CharField(choices=[('manga', 'Манга'), ('manhwa', 'Манхва'), ('manhua', 'Маньхуа'), ('one-shot', 'Ваншот'), ('doujinshi', 'Додзинси'), ('other', 'Другое')], default='manga', max_length=20)),
                ('age_rating', models.CharField(blank=True, max_length=4, null=True)),
                ('year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('banner_url', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('work_status', models.CharField(choices=[('ongoing', 'Онгоинг'), ('completed', 'Завершено'), ('hiatus', 'Пауза'), ('frozen', 'Заморожено'), ('announced', 'Анонс')], default='ongoing', max_length=20)),
                ('links', models.JSONField(blank=True, default=list)),
                ('categories', models.ManyToManyField(blank=True, related_name='manga', to='manga.category')),
                ('genres', models.ManyToManyField(blank=True, related_name='manga', to='manga.genre')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('translation_status', models.CharField(choices=[('in_progress', 'Перевод идёт'), ('completed', 'Перевод завершён'), ('dropped', 'Брошено')], default='in_progress', max_length=20)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='manga.manga')),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='manga.translatorpublisher')),
            ],
            options={
                'ordering': ('translator__name',),
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.DecimalField(decimal_places=2, max_digits=5)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('volume', models.PositiveIntegerField(blank=True, null=True)),
                ('pages_count', models.PositiveIntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='manga.edition')),
            ],
            options={
                'ordering': ('-number',),
                'indexes': [models.Index(fields=['edition', 'number'], name='manga_chapt_edition_a9becd_idx'), models.Index(fields=['published_at'], name='manga_chapt_publish_fb81b8_idx')],
                'unique_together': {('edition', 'number')},
            },
        ),
        migrations.AddIndex(
            model_name='manga',
            index=models.Index(fields=['title_ru'], name='manga_manga_title_r_0636c0_idx'),
        ),
        migrations.AddIndex(
            model_name='manga',
            index=models.Index(fields=['title_en'], name='manga_manga_title_e_b7a76a_idx'),
        ),
        migrations.AddIndex(
            model_name='manga',
            index=models.Index(fields=['type'], name='manga_manga_type_791a13_idx'),
        ),
        migrations.AddIndex(
            model_name='manga',
            index=models.Index(fields=['work_status'], name='manga_manga_work_st_8a61ac_idx'),
        ),
        migrations.AddIndex(
            model_name='manga',
            index=models.Index(fields=['year'], name='manga_manga_year_5097b2_idx'),
        ),
        migrations.AddIndex(
            model_name='edition',
            index=models.Index(fields=['manga', 'translator'], name='manga_editi_manga_i_e8129c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='edition',
            unique_together={('manga', 'translator')},
        ),
    ]
