# Generated by Django 5.2.5 on 2025-08-28 19:02

import django.db.models.deletion
import manga.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_chapters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TranslatorMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('moderator', 'Модератор'), ('publisher', 'Паблишер'), ('member', 'Участник')], default='member', max_length=16)),
                ('title', models.CharField(blank=True, help_text='Необязательная подпись в команде (например: верстальщик, редактор).', max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('translator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translatormember_set', to='manga.translatorpublisher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translator_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('translator__name', 'user_id'),
            },
        ),
        migrations.AddField(
            model_name='translatorpublisher',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='translator_groups', through='manga.TranslatorMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ChapterPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to=manga.models.page_upload_to)),
                ('order', models.PositiveIntegerField(db_index=True, default=1)),
                ('type', models.CharField(choices=[('page', 'Страница')], default='page', max_length=16)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='manga.chapter')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_pages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order',),
                'indexes': [models.Index(fields=['chapter', 'order'], name='manga_chapt_chapter_f7cef9_idx')],
                'unique_together': {('chapter', 'order')},
            },
        ),
        migrations.AddIndex(
            model_name='translatormember',
            index=models.Index(fields=['translator', 'role'], name='manga_trans_transla_45fd5b_idx'),
        ),
        migrations.AddIndex(
            model_name='translatormember',
            index=models.Index(fields=['user', 'role'], name='manga_trans_user_id_e39356_idx'),
        ),
        migrations.AddConstraint(
            model_name='translatormember',
            constraint=models.UniqueConstraint(fields=('translator', 'user'), name='uniq_translator_user'),
        ),
    ]
