# Generated by Django 5.2.5 on 2025-10-12 19:05

import django.core.validators
import manga.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_chapter_uploaded_by_translatormember_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='banner_url',
        ),
        migrations.RemoveField(
            model_name='manga',
            name='poster_url',
        ),
        migrations.AddField(
            model_name='manga',
            name='banner',
            field=models.ImageField(blank=True, help_text='Шапка/баннер (jpg/png/webp)', null=True, upload_to=manga.models.banner_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='manga',
            name='poster',
            field=models.ImageField(blank=True, help_text='Постер манги (jpg/png/webp)', null=True, upload_to=manga.models.poster_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='translatormember',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
