# Generated by Django 5.2.5 on 2025-12-27 00:36

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField()),
                ('max_total_uses', models.PositiveIntegerField(default=1)),
                ('max_uses_per_user', models.PositiveIntegerField(default=1)),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed amount')], default='percent', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField()),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='promo.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'promo'], name='promo_promo_user_id_fc3eea_idx')],
                'constraints': [models.UniqueConstraint(fields=('promo', 'user'), name='uniq_promo_user_once')],
            },
        ),
    ]
