# Generated by Django 5.2.5 on 2025-12-27 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customitem', '0004_alter_item_type'),
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBalanceBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('RUB', 'Рубли'), ('AKI', 'AkiCoin')], default='AKI', max_length=3)),
                ('bonus_type', models.CharField(choices=[('fixed', 'Fixed'), ('percent', 'Percent of topup')], default='fixed', max_length=10)),
                ('bonus_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_topup_minor', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromoItemGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PromoTopupDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('RUB', 'Рубли'), ('AKI', 'AkiCoin')], default='RUB', max_length=3)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_topup_minor', models.BigIntegerField(default=0)),
                ('max_discount_minor', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='promoredemption',
            name='promo_promo_user_id_fc3eea_idx',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='discount_type',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='discount_value',
        ),
        migrations.RemoveField(
            model_name='promocode',
            name='min_amount',
        ),
        migrations.AddField(
            model_name='promoredemption',
            name='context',
            field=models.CharField(default='manual', max_length=16),
        ),
        migrations.AddField(
            model_name='promoredemption',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='promoredemption',
            name='topup_amount_minor',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promobalancebonus',
            name='promo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance_bonus', to='promo.promocode'),
        ),
        migrations.AddField(
            model_name='promoitemgrant',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customitem.item'),
        ),
        migrations.AddField(
            model_name='promoitemgrant',
            name='promo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item_grant', to='promo.promocode'),
        ),
        migrations.AddField(
            model_name='promotopupdiscount',
            name='promo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='topup_discount', to='promo.promocode'),
        ),
    ]
