# Generated by Django 5.2.5 on 2025-12-29 22:48

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_promobalancebonus_promoitemgrant_promotopupdiscount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='promoredemption',
            name='uniq_promo_user_once',
        ),
        migrations.AddField(
            model_name='promoredemption',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promoredemption',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='promoredemption',
            name='payment_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='promoredemption',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='promoredemption',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='promoredemption',
            name='topup_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='promoredemption',
            name='redeemed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='promoredemption',
            index=models.Index(fields=['promo', 'user', 'status', 'redeemed_at'], name='promo_promo_promo_i_7b801f_idx'),
        ),
        migrations.AddIndex(
            model_name='promoredemption',
            index=models.Index(fields=['payment_id'], name='promo_promo_payment_19a0ff_idx'),
        ),
        migrations.AddIndex(
            model_name='promoredemption',
            index=models.Index(fields=['topup_id'], name='promo_promo_topup_i_1ad75b_idx'),
        ),
        migrations.AddIndex(
            model_name='promoredemption',
            index=models.Index(fields=['idempotency_key'], name='promo_promo_idempot_1fcbcc_idx'),
        ),
        migrations.AddConstraint(
            model_name='promoredemption',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'applied')), fields=('promo', 'user'), name='uniq_promo_user_applied'),
        ),
        migrations.AddConstraint(
            model_name='promoredemption',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('idempotency_key',), name='uniq_promo_idempotency_key'),
        ),
    ]
