# Generated by Django 5.2.5 on 2025-08-18 20:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LicenseOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MDLTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('source', models.CharField(choices=[('kp', 'KinoPoisk'), ('shikimori', 'Shikimori'), ('mdl', 'MyDramaList'), ('all', 'All sources')], default='all', max_length=16)),
                ('slug', models.SlugField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['source', 'slug'], name='kodik_genre_source_6b6ffd_idx'), models.Index(fields=['source', 'name'], name='kodik_genre_source_9793c5_idx')],
                'unique_together': {('slug', 'source')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('kodik_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('type', models.CharField(db_index=True, max_length=64)),
                ('link', models.URLField(max_length=1000)),
                ('title', models.CharField(max_length=300)),
                ('title_orig', models.CharField(blank=True, default='', max_length=300)),
                ('other_title', models.CharField(blank=True, default='', max_length=300)),
                ('year', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('quality', models.CharField(blank=True, default='', max_length=120)),
                ('camrip', models.BooleanField(blank=True, null=True)),
                ('lgbt', models.BooleanField(blank=True, null=True)),
                ('kinopoisk_id', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('imdb_id', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('mdl_id', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('worldart_link', models.URLField(blank=True, default='', max_length=1000)),
                ('shikimori_id', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_season', models.PositiveIntegerField(blank=True, null=True)),
                ('last_episode', models.PositiveIntegerField(blank=True, null=True)),
                ('episodes_count', models.PositiveIntegerField(blank=True, null=True)),
                ('screenshots', models.JSONField(blank=True, default=list)),
                ('poster_url', models.URLField(blank=True, default='', max_length=1000)),
                ('blocked_seasons', models.JSONField(blank=True, default=dict)),
                ('blocked_countries', models.ManyToManyField(blank=True, related_name='blocked_materials', to='kodik.country')),
                ('genres', models.ManyToManyField(blank=True, related_name='materials', to='kodik.genre')),
                ('license_owners', models.ManyToManyField(blank=True, related_name='materials', to='kodik.licenseowner')),
                ('production_countries', models.ManyToManyField(blank=True, related_name='materials', to='kodik.country')),
                ('mdl_tags', models.ManyToManyField(blank=True, related_name='materials', to='kodik.mdltag')),
                ('studios', models.ManyToManyField(blank=True, related_name='materials', to='kodik.studio')),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('anime_title', models.CharField(blank=True, default='', max_length=300)),
                ('title_en', models.CharField(blank=True, default='', max_length=300)),
                ('other_titles', models.JSONField(blank=True, default=list)),
                ('other_titles_en', models.JSONField(blank=True, default=list)),
                ('other_titles_jp', models.JSONField(blank=True, default=list)),
                ('anime_license_name', models.CharField(blank=True, default='', max_length=200)),
                ('anime_kind', models.CharField(blank=True, default='', max_length=40)),
                ('all_status', models.CharField(blank=True, default='', max_length=40)),
                ('anime_status', models.CharField(blank=True, default='', max_length=40)),
                ('drama_status', models.CharField(blank=True, default='', max_length=40)),
                ('tagline', models.CharField(blank=True, default='', max_length=400)),
                ('description', models.TextField(blank=True, default='')),
                ('anime_description', models.TextField(blank=True, default='')),
                ('poster_url', models.URLField(blank=True, default='', max_length=1000)),
                ('anime_poster_url', models.URLField(blank=True, default='', max_length=1000)),
                ('drama_poster_url', models.URLField(blank=True, default='', max_length=1000)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('kinopoisk_rating', models.FloatField(blank=True, null=True)),
                ('kinopoisk_votes', models.PositiveIntegerField(blank=True, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('imdb_votes', models.PositiveIntegerField(blank=True, null=True)),
                ('shikimori_rating', models.FloatField(blank=True, null=True)),
                ('shikimori_votes', models.PositiveIntegerField(blank=True, null=True)),
                ('mydramalist_rating', models.FloatField(blank=True, null=True)),
                ('mydramalist_votes', models.PositiveIntegerField(blank=True, null=True)),
                ('premiere_ru', models.DateField(blank=True, null=True)),
                ('premiere_world', models.DateField(blank=True, null=True)),
                ('aired_at', models.DateField(blank=True, null=True)),
                ('released_at', models.DateField(blank=True, null=True)),
                ('next_episode_at', models.DateTimeField(blank=True, null=True)),
                ('rating_mpaa', models.CharField(blank=True, default='', max_length=16)),
                ('minimal_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('episodes_total', models.PositiveIntegerField(blank=True, null=True)),
                ('episodes_aired', models.PositiveIntegerField(blank=True, null=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extra', to='kodik.material')),
            ],
            options={
                'verbose_name': 'Material extra',
                'verbose_name_plural': 'Materials extra',
            },
        ),
        migrations.CreateModel(
            name='MaterialVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='kodik.material')),
            ],
            options={
                'ordering': ['material_id'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('link', models.URLField(blank=True, default='', max_length=1000)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='kodik.materialversion')),
            ],
            options={
                'ordering': ['version', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('link', models.URLField(max_length=1000)),
                ('title', models.CharField(blank=True, default='', max_length=300)),
                ('screenshots', models.JSONField(blank=True, default=list)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='kodik.season')),
            ],
            options={
                'ordering': ['season', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('voice', 'voice'), ('subtitles', 'subtitles')], max_length=16)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['ext_id'], name='kodik_trans_ext_id_5c3483_idx')],
            },
        ),
        migrations.AddField(
            model_name='materialversion',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='kodik.translation'),
        ),
        migrations.AddField(
            model_name='material',
            name='translation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials_legacy', to='kodik.translation'),
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('actor', 'actor'), ('director', 'director'), ('producer', 'producer'), ('writer', 'writer'), ('composer', 'composer'), ('editor', 'editor'), ('designer', 'designer'), ('operator', 'operator')], db_index=True, max_length=16)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='kodik.material')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='kodik.person')),
            ],
            options={
                'indexes': [models.Index(fields=['material', 'role'], name='kodik_credi_materia_77b4d0_idx'), models.Index(fields=['person', 'role'], name='kodik_credi_person__8672e2_idx')],
                'unique_together': {('material', 'person', 'role')},
            },
        ),
        migrations.AddIndex(
            model_name='season',
            index=models.Index(fields=['version', 'number'], name='kodik_seaso_version_ac8d97_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='season',
            unique_together={('version', 'number')},
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['season', 'number'], name='kodik_episo_season__0e4a19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('season', 'number')},
        ),
        migrations.AddIndex(
            model_name='materialversion',
            index=models.Index(fields=['material', 'translation'], name='kodik_mater_materia_a3d8e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='materialversion',
            unique_together={('material', 'translation')},
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['type', 'updated_at'], name='kodik_mater_type_a35479_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['year'], name='kodik_mater_year_fa5e61_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['kinopoisk_id'], name='kodik_mater_kinopoi_398c93_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['imdb_id'], name='kodik_mater_imdb_id_528b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['shikimori_id'], name='kodik_mater_shikimo_f8a16b_idx'),
        ),
    ]
