# Generated by Django 5.2.5 on 2025-09-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodik', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialextra',
            options={},
        ),
        migrations.AddField(
            model_name='materialversion',
            name='movie_link',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='material',
            name='link',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddIndex(
            model_name='materialversion',
            index=models.Index(fields=['material'], name='kodik_mater_materia_958bea_idx'),
        ),
    ]
