# Generated by Django 5.2.5 on 2025-09-17 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodik', '0002_alter_materialextra_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credit',
            options={'ordering': ['material', 'role', 'order']},
        ),
        migrations.RemoveIndex(
            model_name='credit',
            name='kodik_credi_materia_77b4d0_idx',
        ),
        migrations.AddField(
            model_name='credit',
            name='character_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='credit',
            name='note',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='credit',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='avatar_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='person',
            name='banner_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='kodik.country'),
        ),
        migrations.AddField(
            model_name='person',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='imdb_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='person',
            name='kinopoisk_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='person',
            name='photo_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='person',
            name='shikimori_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='person',
            name='socials',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='translation',
            name='aliases',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='translation',
            name='avatar_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='translation',
            name='banner_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='translation',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='kodik.country'),
        ),
        migrations.AddField(
            model_name='translation',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='translation',
            name='founded_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='poster_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='translation',
            name='website_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['material', 'role', 'order'], name='kodik_credi_materia_ded515_idx'),
        ),
    ]
