# Generated by Django 5.2.5 on 2025-09-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodik', '0003_alter_credit_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='imdb_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='material',
            name='kinopoisk_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='material',
            name='mdl_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='material',
            name='shikimori_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='imdb_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='kinopoisk_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='person',
            name='shikimori_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
    ]
