# Generated by Django 5.2.5 on 2025-10-13 19:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodik', '0004_alter_material_imdb_id_alter_material_kinopoisk_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AkiUserRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aki_user_ratings', to='kodik.material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aki_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['material', 'user'], name='kodik_akius_materia_00e444_idx'), models.Index(fields=['material', 'score'], name='kodik_akius_materia_209ef0_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 10)), name='aki_score_range_0_10')],
                'unique_together': {('material', 'user')},
            },
        ),
        migrations.CreateModel(
            name='MaterialComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('published', 'published'), ('pending', 'pending'), ('hidden', 'hidden')], db_index=True, default='published', max_length=16)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('replies_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='kodik.material')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='kodik.materialcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['material', 'status', 'is_deleted', '-created_at'], name='kodik_mater_materia_9f28dc_idx'), models.Index(fields=['parent', '-created_at'], name='kodik_mater_parent__1fa4b7_idx')],
            },
        ),
    ]
