# Generated by Django 5.2.5 on 2025-10-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodik', '0005_akiuserrating_materialcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialextra',
            name='aki_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='materialextra',
            name='aki_votes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='materialextra',
            name='comments_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
