# Generated by Django 5.2.5 on 2025-10-13 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodik', '0006_materialextra_aki_rating_materialextra_aki_votes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='materialextra',
            name='aki_rating',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='materialextra',
            name='aki_votes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='materialextra',
            index=models.Index(fields=['comments_count'], name='kodik_mater_comment_ba0040_idx'),
        ),
        migrations.AddIndex(
            model_name='materialextra',
            index=models.Index(fields=['aki_votes'], name='kodik_mater_aki_vot_200a1a_idx'),
        ),
        migrations.AddIndex(
            model_name='materialextra',
            index=models.Index(fields=['aki_rating'], name='kodik_mater_aki_rat_e7a045_idx'),
        ),
        migrations.AddField(
            model_name='materialcommentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='kodik.materialcomment'),
        ),
        migrations.AddField(
            model_name='materialcommentlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='materialcommentlike',
            index=models.Index(fields=['comment', 'user'], name='kodik_mater_comment_a76a81_idx'),
        ),
        migrations.AddIndex(
            model_name='materialcommentlike',
            index=models.Index(fields=['comment'], name='kodik_mater_comment_ccaaa8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='materialcommentlike',
            unique_together={('comment', 'user')},
        ),
    ]
