# Generated by Django 5.2.5 on 2025-10-13 22:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodik', '0007_materialcommentlike_alter_materialextra_aki_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialcomment',
            options={'ordering': ('created_at',)},
        ),
        migrations.RemoveIndex(
            model_name='materialcomment',
            name='kodik_mater_materia_9f28dc_idx',
        ),
        migrations.RemoveIndex(
            model_name='materialcomment',
            name='kodik_mater_parent__1fa4b7_idx',
        ),
        migrations.RenameField(
            model_name='materialcomment',
            old_name='body',
            new_name='content',
        ),
        migrations.AddIndex(
            model_name='materialcomment',
            index=models.Index(fields=['material', 'status', 'is_deleted', 'created_at'], name='kodik_mater_materia_3dbf70_idx'),
        ),
        migrations.AddIndex(
            model_name='materialcomment',
            index=models.Index(fields=['parent', 'created_at'], name='kodik_mater_parent__02dd64_idx'),
        ),
    ]
