# Generated by Django 5.2.5 on 2025-11-20 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kodik', '0008_alter_materialcomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialextra',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='materialextra',
            index=models.Index(fields=['views_count'], name='kodik_mater_views_c_637482_idx'),
        ),
    ]
