# Generated by Django 5.2.5 on 2025-08-28 23:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('avatar_static', 'Аватар (статичный)'), ('avatar_anim', 'Аватар (аним.)'), ('header_anim', 'Шапка (аним.)'), ('theme', 'Тема профиля/ридера')], db_index=True, max_length=32)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='items/files/')),
                ('file_url', models.URLField(blank=True, null=True)),
                ('preview', models.ImageField(blank=True, null=True, upload_to='items/previews/')),
                ('is_animated', models.BooleanField(default=False)),
                ('mime', models.CharField(blank=True, help_text='Напр.: image/webp, video/webm', max_length=80)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('rarity', models.CharField(choices=[('common', 'Обычный'), ('rare', 'Редкий'), ('epic', 'Эпический'), ('legend', 'Легендарный')], default='common', max_length=16)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Произвольные настройки/цвета/параметры темы')),
                ('price_aki', models.PositiveIntegerField(default=0, help_text='Цена в AkiCoin (целые). 0 = нельзя купить (например, трофей).')),
                ('limited_total', models.PositiveIntegerField(blank=True, help_text='Общий лимит продаж (опционально)', null=True)),
                ('limited_sold', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['type', 'is_active'], name='customitem__type_14c4dc_idx'), models.Index(fields=['rarity'], name='customitem__rarity_f34363_idx')],
            },
        ),
        migrations.CreateModel(
            name='AppliedCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applied_custom', to=settings.AUTH_USER_MODEL)),
                ('avatar_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_as_avatar', to='customitem.item')),
                ('header_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_as_header', to='customitem.item')),
                ('theme_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_as_theme', to='customitem.item')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('purchase', 'Покупка'), ('grant', 'Выдача (админ)'), ('achieve', 'Ачивка'), ('gift', 'Подарок')], default='purchase', max_length=16)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('acquired_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='customitem.item')),
            ],
            options={
                'ordering': ('-acquired_at',),
                'indexes': [models.Index(fields=['user', 'acquired_at'], name='customitem__user_id_8798a1_idx'), models.Index(fields=['item'], name='customitem__item_id_694833_idx')],
                'unique_together': {('user', 'item')},
            },
        ),
    ]
