# Generated by Django 5.2.5 on 2025-08-28 23:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customitem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appliedcustomization',
            options={'verbose_name': 'Активные предметы пользователя', 'verbose_name_plural': 'Активные предметы пользователей'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ('-acquired_at',), 'verbose_name': 'Запись инвентаря', 'verbose_name_plural': 'Инвентарь'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('-created_at',), 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterField(
            model_name='appliedcustomization',
            name='avatar_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_as_avatar', to='customitem.item', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='appliedcustomization',
            name='header_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_as_header', to='customitem.item', verbose_name='Шапка'),
        ),
        migrations.AlterField(
            model_name='appliedcustomization',
            name='theme_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_as_theme', to='customitem.item', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='appliedcustomization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='appliedcustomization',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applied_custom', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='acquired_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Получено'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='customitem.item', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='source',
            field=models.CharField(choices=[('purchase', 'Покупка'), ('grant', 'Выдача (админ)'), ('achieve', 'Ачивка'), ('gift', 'Подарок')], default='purchase', max_length=16, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='item',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Произвольные настройки/цвета/параметры темы (JSON).', verbose_name='Атрибуты'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='item',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Длительность (мс)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, help_text='Загрузите файл предмета (например, .webp/.webm) либо укажите внешний URL ниже.', null=True, upload_to='items/files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='item',
            name='file_url',
            field=models.URLField(blank=True, help_text='Альтернатива загрузке файла.', null=True, verbose_name='Внешний URL файла'),
        ),
        migrations.AlterField(
            model_name='item',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_animated',
            field=models.BooleanField(default=False, verbose_name='Анимированный'),
        ),
        migrations.AlterField(
            model_name='item',
            name='limited_sold',
            field=models.PositiveIntegerField(default=0, verbose_name='Продано'),
        ),
        migrations.AlterField(
            model_name='item',
            name='limited_total',
            field=models.PositiveIntegerField(blank=True, help_text='Общий лимит продаж; оставьте пустым, если безлимит.', null=True, verbose_name='Лимит продаж (всего)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='mime',
            field=models.CharField(blank=True, help_text='Напр.: image/webp, video/webm', max_length=80, verbose_name='MIME-тип'),
        ),
        migrations.AlterField(
            model_name='item',
            name='preview',
            field=models.ImageField(blank=True, help_text='Статичное превью для списка/админки.', null=True, upload_to='items/previews/', verbose_name='Превью (картинка)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_aki',
            field=models.PositiveIntegerField(default=0, help_text='Цена в AkiCoin (целые). 0 — нельзя купить (например, трофей).', verbose_name='Цена (AKI)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='rarity',
            field=models.CharField(choices=[('common', 'Обычный'), ('rare', 'Редкий'), ('epic', 'Эпический'), ('legend', 'Легендарный')], default='common', max_length=16, verbose_name='Редкость'),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(help_text='URL-идентификатор. Генерируется из названия.', max_length=160, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=160, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('avatar_static', 'Аватар (статичный)'), ('avatar_anim', 'Аватар (аним.)'), ('header_anim', 'Шапка (аним.)'), ('theme', 'Тема профиля/ридера')], db_index=True, max_length=32, verbose_name='Тип предмета'),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='item',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина'),
        ),
    ]
