# Generated by Django 5.2.5 on 2025-09-01 18:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customitem', '0002_alter_appliedcustomization_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Инвентарь (запись)', 'verbose_name_plural': 'Инвентарь'},
        ),
        migrations.RemoveIndex(
            model_name='inventory',
            name='customitem__item_id_694833_idx',
        ),
        migrations.RemoveIndex(
            model_name='item',
            name='customitem__rarity_f34363_idx',
        ),
        migrations.AddField(
            model_name='appliedcustomization',
            name='frame_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_as_frame', to='customitem.item', verbose_name='Рамка аватара'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='acquired_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Получено'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='note',
            field=models.CharField(blank=True, max_length=180, verbose_name='Заметка'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='source',
            field=models.CharField(choices=[('purchase', 'Покупка'), ('gift', 'Подарок/выдача'), ('achieve', 'Ачивка')], default='purchase', max_length=16, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='item',
            name='file_url',
            field=models.URLField(blank=True, help_text='Если файл хранится вне нашего медиа.', null=True, verbose_name='Внешний URL файла'),
        ),
        migrations.AlterField(
            model_name='item',
            name='limited_total',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Лимит выпущенных'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('avatar_static', 'Аватар (статичный)'), ('avatar_anim', 'Аватар (аним.)'), ('header_anim', 'Шапка (аним.)'), ('theme', 'Тема профиля/ридера'), ('avatar_frame', 'Рамка для аватара')], db_index=True, max_length=32, verbose_name='Тип предмета'),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['slug'], name='customitem__slug_4a0c5f_idx'),
        ),
    ]
