# Generated by Django 5.2.5 on 2025-12-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customitem', '0003_alter_inventory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('avatar', 'Аватар'), ('header', 'Шапка'), ('theme', 'Тема профиля/ридера'), ('avatar_frame', 'Рамка для аватара')], db_index=True, max_length=32, verbose_name='Тип предмета'),
        ),
    ]
