# Generated by Django 5.2.5 on 2025-09-06 17:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kodik', '0001_initial'),
        ('manga', '0002_chapter_uploaded_by_translatormember_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Слаг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('thread_type', models.CharField(choices=[('general', 'Общее'), ('anime', 'Аниме'), ('manga', 'Манга'), ('site', 'Сайт')], db_index=True, default='general', max_length=16, verbose_name='Тип темы')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Слаг')),
                ('content', models.TextField(verbose_name='Контент')),
                ('comments_count', models.PositiveIntegerField(default=0, verbose_name='Комментариев')),
                ('last_activity_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Последняя активность')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Закрыта')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Закреплена')),
                ('anime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forum_threads', to='kodik.material', verbose_name='Аниме (Kodik)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forum_threads', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='threads', to='forum.category', verbose_name='Категория')),
                ('manga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forum_threads', to='manga.manga', verbose_name='Манга')),
                ('publish_as_team', models.ForeignKey(blank=True, help_text='Если заполнено — пост отображается от имени команды.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forum_threads', to='manga.translatorpublisher', verbose_name='От имени команды')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ('-is_pinned', '-last_activity_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('content', models.TextField(verbose_name='Контент')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалён')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forum_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('in_reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='forum.comment', verbose_name='Ответ на')),
                ('publish_as_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forum_comments', to='manga.translatorpublisher', verbose_name='От имени команды')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='forum.thread', verbose_name='Тема')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['thread_type', 'last_activity_at'], name='forum_threa_thread__0927ad_idx'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['category', 'last_activity_at'], name='forum_threa_categor_0bf4b5_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['thread', 'created_at'], name='forum_comme_thread__4177b4_idx'),
        ),
    ]
