# Generated by Django 5.2.5 on 2025-10-13 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('manga', '0003_remove_manga_banner_url_remove_manga_poster_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='comment',
            name='forum_comme_thread__4177b4_idx',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='in_reply_to',
        ),
        migrations.AddField(
            model_name='comment',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Закреплён'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.comment', verbose_name='Ответ на'),
        ),
        migrations.AddField(
            model_name='comment',
            name='replies_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликован'), ('pending', 'На модерации'), ('hidden', 'Скрыт')], db_index=True, default='published', max_length=16),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Удалён'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['thread', 'status', 'is_deleted', 'created_at'], name='forum_comme_thread__83c880_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', 'created_at'], name='forum_comme_parent__12240b_idx'),
        ),
    ]
