# Generated by Django 5.2.5 on 2025-10-20 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_remove_comment_forum_comme_thread__4177b4_idx_and_more'),
        ('kodik', '0008_alter_materialcomment_options_and_more'),
        ('manga', '0003_remove_manga_banner_url_remove_manga_poster_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Тег')),
                ('slug', models.SlugField(max_length=72, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='ThreadAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('kind', models.CharField(choices=[('image', 'Картинка'), ('file', 'Файл'), ('link', 'Ссылка')], default='image', max_length=12)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='forum/attachments/%Y/%m/')),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ThreadKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название типа')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Слаг')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('allow_anime', models.BooleanField(default=False, verbose_name='Разрешить привязку к аниме')),
                ('allow_manga', models.BooleanField(default=False, verbose_name='Разрешить привязку к манге')),
                ('allow_publish_as_team', models.BooleanField(default=True, verbose_name='Разрешить публиковать от имени команды')),
            ],
            options={
                'verbose_name': 'Тип темы',
                'verbose_name_plural': 'Типы тем',
                'ordering': ('order', 'title'),
            },
        ),
        migrations.CreateModel(
            name='ThreadPublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('role', models.CharField(choices=[('primary', 'Основной релиз'), ('partner', 'Партнёр'), ('source', 'Источник'), ('other', 'Другое')], default='primary', max_length=16, verbose_name='Роль')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Связь темы с командой',
                'verbose_name_plural': 'Связи темы с командами',
            },
        ),
        migrations.CreateModel(
            name='TranslatorWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('kind', models.CharField(choices=[('anime', 'Аниме'), ('manga', 'Манга')], db_index=True, max_length=16)),
                ('role', models.CharField(choices=[('subs', 'Субтитры'), ('dub', 'Озвучка'), ('edit', 'Редактура'), ('raw', 'Raw/Сырые'), ('other', 'Другое')], default='subs', max_length=16)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Работа переводчика',
                'verbose_name_plural': 'Работы переводчиков',
            },
        ),
        migrations.RemoveIndex(
            model_name='thread',
            name='forum_threa_thread__0927ad_idx',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='thread_type',
        ),
        migrations.AddField(
            model_name='thread',
            name='extra',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп.мета'),
        ),
        migrations.AddField(
            model_name='thread',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='forum/posters/%Y/%m/', verbose_name='Постер'),
        ),
        migrations.AddField(
            model_name='thread',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='threads', to='forum.tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='threadattachment',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='forum.thread'),
        ),
        migrations.AddField(
            model_name='thread',
            name='kind',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='threads', to='forum.threadkind', verbose_name='Тип темы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='threadpublisher',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thread_links', to='manga.translatorpublisher'),
        ),
        migrations.AddField(
            model_name='threadpublisher',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_publishers', to='forum.thread'),
        ),
        migrations.AddField(
            model_name='thread',
            name='publishers',
            field=models.ManyToManyField(blank=True, related_name='related_threads', through='forum.ThreadPublisher', to='manga.translatorpublisher', verbose_name='Команды переводчиков (связанные с темой)'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['kind', 'last_activity_at'], name='forum_threa_kind_id_afb739_idx'),
        ),
        migrations.AddField(
            model_name='translatorwork',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translator_works', to='kodik.material'),
        ),
        migrations.AddField(
            model_name='translatorwork',
            name='manga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translator_works', to='manga.manga'),
        ),
        migrations.AddField(
            model_name='translatorwork',
            name='translator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='works', to='manga.translatorpublisher'),
        ),
        migrations.AlterUniqueTogether(
            name='threadpublisher',
            unique_together={('thread', 'publisher', 'role')},
        ),
        migrations.AddIndex(
            model_name='translatorwork',
            index=models.Index(fields=['kind', 'translator'], name='forum_trans_kind_71797c_idx'),
        ),
        migrations.AddConstraint(
            model_name='translatorwork',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('anime__isnull', False), ('kind', 'anime'), ('manga__isnull', True)), models.Q(('anime__isnull', True), ('kind', 'manga'), ('manga__isnull', False)), _connector='OR'), name='tw_kind_consistency'),
        ),
    ]
