# Generated by Django 5.2.5 on 2025-10-27 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='content_html',
            field=models.TextField(blank=True, null=True, verbose_name='Контент (HTML)'),
        ),
    ]
