# Generated by Django 5.2.5 on 2025-11-01 20:20

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_content_post_content_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_html',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
