# Generated by Django 5.2.5 on 2025-11-01 20:45

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_html',
            field=tinymce.models.HTMLField(verbose_name='Содержимое'),
        ),
    ]
