# Generated by Django 5.2.5 on 2025-12-01 03:27

import craft.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kodik', '0009_materialextra_views_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderMaterialContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(help_text='Крупное изображение для фоновой шапки.', upload_to=craft.models.header_poster_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Постер для шапки')),
                ('is_active', models.BooleanField(default=True, help_text='Если выключено — не участвует в выборке для главной.', verbose_name='Показывать')),
                ('position', models.PositiveIntegerField(default=0, help_text='Для сортировки нескольких шапок.', verbose_name='Позиция')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='header_content', to='kodik.material', verbose_name='Материал Kodik')),
            ],
            options={
                'verbose_name': 'Шапка материала',
                'verbose_name_plural': 'Шапки материалов',
                'ordering': ('position', '-created_at'),
                'indexes': [models.Index(fields=['is_active', 'position'], name='craft_heade_is_acti_e594ff_idx')],
            },
        ),
    ]
