# Generated by Django 5.2.5 on 2025-12-26 22:48

import craft.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='headermaterialcontent',
            name='poster',
            field=models.ImageField(help_text='Крупное изображение для фоновой шапки.', upload_to=craft.models.header_poster_upload_to, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'gif'])], verbose_name='Постер для шапки'),
        ),
    ]
