# Generated by Django 5.2.5 on 2025-08-28 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customitem', '0002_alter_appliedcustomization_options_and_more'),
        ('economy', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ('-created_at',), 'verbose_name': 'Оффер', 'verbose_name_plural': 'Офферы'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ('-created_at',), 'verbose_name': 'Покупка', 'verbose_name_plural': 'Покупки'},
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание продаж'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='offer', to='customitem.item', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price_override_aki',
            field=models.PositiveIntegerField(blank=True, help_text='Если задано — заменяет Item.price_aki.', null=True, verbose_name='Цена (override, AKI)'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало продаж'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='customitem.item', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='price_aki',
            field=models.PositiveIntegerField(verbose_name='Цена (AKI)'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('success', 'Успешно'), ('failed', 'Ошибка')], default='success', max_length=12, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item_purchases', to='economy.transaction', verbose_name='Транзакция'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
